version: '3.8'

services:
  php:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build:
      context: . # Build context is the root directory
      dockerfile: ./docker/php/Dockerfile # Path to Dockerfile
    container_name: product-api-php
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: product-api-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: ${DB_TYPE}
    container_name: product-api-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "27017:27017" # MongoDB
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local