version: '3.8'

services:
  php:
    build: ./docker/php
    container_name: product-api-php
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: product-api-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: ${DB_TYPE}-latest
    container_name: product-api-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "27017:27017" # MongoDB
      - "5432:5432"  # PostgreSQL
    networks:
      - app-network
    volumes:
      - db-data:/data/db

networks:
  app-network:

volumes:
  db-data: